class Note {
  final int? id;  // null for new notes, auto-generated by database
  final String title;
  final String content;

  Note({this.id, required this.title, required this.content});

  // TODO: Create a method to convert Note to Map (for saving to database)
  Map<String, dynamic> toMap() => {
    'title': title,
    'content': content,
  };

  // TODO: Create a factory to convert Map to Note (for loading from database)
  factory Note.fromMap(Map<String, dynamic> map, int id) {
    // Your code here
    return Note(
      id: id,
      title: map['title'] as String,
      content: map['content'] as String,
    );
  }
}